name: Build ESP8684

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-arduino-cli@v2

      - name: Update index
        run: arduino-cli core update-index

      - name: Install ESP32 Core
        run: |
          arduino-cli core install esp32:esp32

      - name: Compile
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32c2 \
            --output-dir build \
            .

      - name: Upload BIN
        uses: actions/upload-artifact@v4
        with:
          name: ESP8684_BIN
          path: build/*
