name: Build ESP8684

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install PlatformIO
      run: |
        pip install platformio

    - name: Build
      run: |
        pio platform update
        pio pkg update
        pio run

    - name: Upload BIN
      uses: actions/upload-artifact@v4
      with:
        name: ESP8684_BIN
        path: |
          .pio/build/esp32c2/*.bin
